---
- name: Installing the Director Packages
  yum: name={{ item }} state=latest
  become: yes
  with_items:
   - rhosp-director-images 
   - rhosp-director-images-ipa
   - python-tripleoclient
  when: install_progress == "undercloud"
  tags:
   - undercloud-install



- name: Ensure undercloud is "{{ state }}"
  shell: "openstack undercloud install"
  become: yes
  become_user: stack
  #async: 7200
  #poll: 0
  when: install_progress == "undercloud"
  tags:
    - undercloud-install
  register: undercloud_install

- name: extract director images
  shell: "for i in /usr/share/rhosp-director-images/overcloud-full-latest-*.tar /usr/share/rhosp-director-images/ironic-python-agent-latest-*.tar; do tar -xvf $i --directory=/home/stack/images/; done"
  become: yes
  become_user: stack
  when: install_progress == "undercloud"
  tags:
    - undercloud-install

- name: inject password to overcloud-full.qcow2
  shell: "virt-customize -a /home/stack/images/overcloud-full.qcow2 --root-password password:{{ project_password }}"
  become: yes
  become_user: stack
  when: install_progress == "undercloud"
  tags:
    - undercloud-install


- name: get the OS_AUTH_URL for undercloud
  shell: "grep OS_AUTH_URL= stackrc  | sed s/OS_AUTH_URL=//g"
  become: yes
  become_user: stack
  register: os_auth_url
  when: install_progress == "undercloud"
  tags:
    - undercloud-install


- name: import images to glance
  shell: "openstack --os-auth-url {{ os_auth_url.stdout }} --os-project-name admin --os-username admin --os-password {{ project_password }} overcloud image upload --image-path /home/stack/images/"
  become: yes
  become_user: stack
  when: install_progress == "undercloud"
  tags:
    - undercloud-install

- name: get ctl subnet uuid
  shell: "openstack --os-auth-url {{ os_auth_url.stdout }} --os-project-name admin --os-username admin --os-password {{ project_password }} subnet list | grep 172 | awk {'print $2'}"
  become: yes
  become_user: stack
  register: subnet_uuid
  when: install_progress == "undercloud"
  tags:
    - undercloud-install


- name: update dns for ctlplane to {{ dns_server }}
  shell: "openstack --os-auth-url {{ os_auth_url.stdout }} --os-project-name admin --os-username admin --os-password {{ project_password }} subnet set --dns-nameserver  {{  dns_server }} {{ subnet_uuid.stdout }}"
  become: yes
  become_user: stack
  when: install_progress == "undercloud"
  tags:
    - undercloud-install
